/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicRobotsDottxtRouteImport } from './routes/api/public/robots[.]txt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRobotsDottxtRoute = ApiPublicRobotsDottxtRouteImport.update({
  id: '/api/public/robots.txt',
  path: '/api/public/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/robots.txt': typeof ApiPublicRobotsDottxtRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/robots.txt' | '/api/public/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/robots.txt' | '/api/public/sitemap.xml'
  id: '__root__' | '/' | '/api/public/robots.txt' | '/api/public/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicRobotsDottxtRoute: typeof ApiPublicRobotsDottxtRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/robots.txt': {
      id: '/api/public/robots.txt'
      path: '/api/public/robots.txt'
      fullPath: '/api/public/robots.txt'
      preLoaderRoute: typeof ApiPublicRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicRobotsDottxtRoute: ApiPublicRobotsDottxtRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
